# Generated by Django 4.0 on 2023-04-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xmail', '0003_auto_20200319_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asyncemailentry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
